INSERT ALL
INTO Bank_Customers (CustId, FirstName, LastName, Class, CustProfile) 
VALUES ('CUST001', 'Emily', 'Chen', 'Premium', '{"age": 32, "income": 80000, "occupation": "Engineer", "address": {"street": "123 Main St", "city": "New York"}}')
INTO Bank_Customers (CustId, FirstName, LastName, Class, CustProfile) 
VALUES ('CUST002', 'Liam', 'Brown', 'Basic', '{"age": 25, "income": 40000, "occupation": "Student", "address": {"street": "456 Elm St", "city": "Chicago"}}')
INTO Bank_Customers (CustId, FirstName, LastName, Class, CustProfile) 
VALUES ('CUST003', 'Ava', 'Davis', 'Elite', '{"age": 42, "income": 150000, "occupation": "Entrepreneur", "address": {"street": "789 Oak St", "city": "San Francisco"}}')
INTO Bank_Customers (CustId, FirstName, LastName, Class, CustProfile) 
VALUES ('CUST004', 'Noah', 'Miller', 'Premium', '{"age": 38, "income": 90000, "occupation": "Doctor", "address": {"street": "901 Maple St", "city": "Los Angeles"}}')
INTO Bank_Customers (CustId, FirstName, LastName, Class, CustProfile) 
VALUES ('CUST005', 'Sophia', 'Garcia', 'Basic', '{"age": 28, "income": 50000, "occupation": "Teacher", "address": {"street": "234 Pine St", "city": "Houston"}}')
SELECT * FROM dual;

INSERT ALL
INTO Bank_Customers (CustId, FirstName, LastName, Class, CustProfile) 
VALUES ('CUST1006', 'Mason', 'Martinez', 'Elite', '{"age": 45, "income": 200000, "occupation": "Lawyer", "address": {"street": "567 Cedar St", "city": "Seattle"}}')
INTO Bank_Customers (CustId, FirstName, LastName, Class, CustProfile) 
VALUES ('CUST1007', 'Isabella', 'Hernandez', 'Premium', '{"age": 35, "income": 70000, "occupation": "Nurse", "address": {"street": "890 Walnut St", "city": "Denver"}}')
INTO Bank_Customers (CustId, FirstName, LastName, Class, CustProfile) 
VALUES ('CUST1008', 'Ethan', 'Lopez', 'Basic', '{"age": 22, "income": 30000, "occupation": "Artist", "address": {"street": "345 Cherry St", "city": "Miami"}}')
INTO Bank_Customers (CustId, FirstName, LastName, Class, CustProfile) 
VALUES ('CUST1009', 'Mia', 'Gonzalez', 'Elite', '{"age": 50, "income": 250000, "occupation": "Executive", "address": {"street": "678 Cypress St", "city": "Dallas"}}')
INTO Bank_Customers (CustId, FirstName, LastName, Class, CustProfile) 
VALUES ('CUST1010', 'Logan', 'Rodriguez', 'Premium', '{"age": 40, "income": 100000, "occupation": "Consultant", "address": {"street": "901 Spruce St", "city": "Boston"}}')
INTO Bank_Customers (CustId, FirstName, LastName, Class, CustProfile) 
VALUES ('CUST1011', 'Charlotte', 'Lewis', 'Basic', '{"age": 29, "income": 45000, "occupation": "Writer", "address": {"street": "234 Fir St", "city": "Washington"}}')
INTO Bank_Customers (CustId, FirstName, LastName, Class, CustProfile) 
VALUES ('CUST1012', 'Alexander', 'Lee', 'Elite', '{"age": 48, "income": 220000, "occupation": "Investor", "address": {"street": "567 Ash St", "city": "Atlanta"}}')
INTO Bank_Customers (CustId, FirstName, LastName, Class, CustProfile) 
VALUES ('CUST1013', 'Amelia', 'Hall', 'Premium', '{"age": 36, "income": 85000, "occupation": "Designer", "address": {"street": "890 Beech St", "city": "Minneapolis"}}')
INTO Bank_Customers (CustId, FirstName, LastName, Class, CustProfile) 
VALUES ('CUST1014', 'Elijah', 'Allen', 'Basic', '{"age": 24, "income": 35000, "occupation": "Developer", "address": {"street": "345 Birch St", "city": "Nashville"}}')
INTO Bank_Customers (CustId, FirstName, LastName, Class, CustProfile) 
VALUES ('CUST1015', 'Harper', 'Scott', 'Elite', '{"age": 52, "income": 280000, "occupation": "CEO", "address": {"street": "678 Hickory St", "city": "Detroit"}}')
INTO Bank_Customers (CustId, FirstName, LastName, Class, CustProfile) 
VALUES ('CUST1016', 'James', 'Mitchell', 'Premium', '{"age": 39, "income": 95000, "occupation": "Manager", "address": {"street": "901 Elm St", "city": "Philadelphia"}}')
INTO Bank_Customers (CustId, FirstName, LastName, Class, CustProfile) 
VALUES ('CUST1017', 'Evelyn', 'Carter', 'Basic', '{"age": 26, "income": 42000, "occupation": "Analyst", "address": {"street": "234 Oak St", "city": "Phoenix"}}')
INTO Bank_Customers (CustId, FirstName, LastName, Class, CustProfile) 
VALUES ('CUST1018', 'Benjamin', 'Phillips', 'Elite', '{"age": 55, "income": 300000, "occupation": "Entrepreneur", "address": {"street": "567 Pine St", "city": "San Jose"}}')
INTO Bank_Customers (CustId, FirstName, LastName, Class, CustProfile) 
VALUES ('CUST1019', 'Abigail', 'Evans', 'Premium', '{"age": 33, "income": 75000, "occupation": "Marketing", "address": {"street": "890 Maple St", "city": "Austin"}}')
INTO Bank_Customers (CustId, FirstName, LastName, Class, CustProfile) 
VALUES ('CUST1020', 'Caleb', 'Turner', 'Basic', '{"age": 20, "income": 25000, "occupation": "Intern", "address": {"street": "345 Cedar St", "city": "Portland"}}')
INTO Bank_Customers (CustId, FirstName, LastName, Class, CustProfile) 
VALUES ('CUST1021', 'Lily', 'Parker', 'Elite', '{"age": 46, "income": 240000, "occupation": "Executive", "address": {"street": "678 Walnut St", "city": "San Diego"}}')
INTO Bank_Customers (CustId, FirstName, LastName, Class, CustProfile) 
VALUES ('CUST1022', 'Jaxon', 'Cooper', 'Premium', '{"age": 41, "income": 110000, "occupation": "Sales", "address": {"street": "901 Spruce St", "city": "Tampa"}}')
INTO Bank_Customers (CustId, FirstName, LastName, Class, CustProfile) 
VALUES ('CUST1023', 'Madison', 'Richardson', 'Basic', '{"age": 27, "income": 38000, "occupation": "Customer Service", "address": {"street": "234 Fir St", "city": "Virginia Beach"}}')
INTO Bank_Customers (CustId, FirstName, LastName, Class, CustProfile) 
VALUES ('CUST1024', 'Gabriel', 'Cox', 'Elite', '{"age": 51, "income": 260000, "occupation": "Investor", "address": {"street": "567 Ash St", "city": "Sacramento"}}')
INTO Bank_Customers (CustId, FirstName, LastName, Class, CustProfile) 
VALUES ('CUST1025', 'Sydney', 'Ward', 'Premium', '{"age": 34, "income": 80000, "occupation": "HR", "address": {"street": "890 Beech St", "city": "Kansas City"}}')
INTO Bank_Customers (CustId, FirstName, LastName, Class, CustProfile) 
VALUES ('CUST1026', 'Emily', 'Chen', 'Premium', '{"age": 32, "income": 80000, "occupation": "Engineer", "address": {"street": "123 Main St", "city": "New York"}}')
INTO Bank_Customers (CustId, FirstName, LastName, Class, CustProfile) 
VALUES ('CUST1027', 'Liam', 'Brown', 'Basic', '{"age": 25, "income": 40000, "occupation": "Student", "address": {"street": "456 Elm St", "city": "Chicago"}}')
INTO Bank_Customers (CustId, FirstName, LastName, Class, CustProfile) 
VALUES ('CUST1028', 'Ava', 'Davis', 'Elite', '{"age": 42, "income": 150000, "occupation": "Entrepreneur", "address": {"street": "789 Oak St", "city": "San Francisco"}}')
INTO Bank_Customers (CustId, FirstName, LastName, Class, CustProfile) 
VALUES ('CUST1029', 'Noah', 'Miller', 'Premium', '{"age": 38, "income": 90000, "occupation": "Doctor", "address": {"street": "901 Maple St", "city": "Los Angeles"}}')
INTO Bank_Customers (CustId, FirstName, LastName, Class, CustProfile) 
VALUES ('CUST1030', 'Sophia', 'Garcia', 'Basic', '{"age": 28, "income": 50000, "occupation": "Teacher", "address": {"street": "234 Pine St", "city": "Houston"}}')
SELECT * FROM dual;

commit;
