  -- Important remove double quotes 

  CREATE TABLE "RETAIL_SHOPPING_FD" 
   (	"ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"INV_NO" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"GENDER" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"AGE" NUMBER, 
	"CATEGORY" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"QTY" NUMBER, 
	"PRICE" NUMBER, 
	"TOTAL_PAY" NUMBER, 
	"METHOD" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"INV_DATE" TIMESTAMP (6), 
	"MALL" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"CUST_ID" NUMBER, 
	"CUST_FIRST_NAME" VARCHAR2(100) COLLATE "USING_NLS_COMP", 
	"CUST_LAST_NAME" VARCHAR2(100) COLLATE "USING_NLS_COMP", 
	"CREDIT_CARD_NO" NUMBER, 
	"TRANS_STATUS" VARCHAR2(20) COLLATE "USING_NLS_COMP", 
	"CUST_CITY" VARCHAR2(100) COLLATE "USING_NLS_COMP", 
	"CUST_STATE_PROVINCE" VARCHAR2(100) COLLATE "USING_NLS_COMP", 
	"TRANSACTION_STATUS" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"COMMENTS" VARCHAR2(500) COLLATE "USING_NLS_COMP", 
	"COUNTRY_ID" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"TX_TIMESTAMP" TIMESTAMP (6), 
	"MERCHANT_ID" NUMBER, 
	"MERCHANT_CITY" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"MERCHANT_REGION" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MERCHANT_STATE" VARCHAR2(100) COLLATE "USING_NLS_COMP", 
	"MERCHANT_PLACE" VARCHAR2(100) COLLATE "USING_NLS_COMP", 
	"LONGITUDE" NUMBER, 
	"LATITUDE" NUMBER, 
	"MERCHANT_PLACE_ID" NUMBER, 
	"CUSTOMER_FULLNAME" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"MERCHANT_FULLNAME" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"INV_TIMESTAMP" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"CC_ID" NUMBER, 
	"TIME_DIFFERENCE_NUMBER" NUMBER, 
	"TX_TYPE" VARCHAR2(20) COLLATE "USING_NLS_COMP", 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;


/*
  CREATE OR REPLACE EDITIONABLE TRIGGER "RETAIL_SHOPPING_FD_TRG" 
before
insert on "RETAIL_SHOPPING_FD"
--insert or update or delete on "RETAIL_SHOPPING_FD"
for each row
declare
        v_ccid number;
        v_n number := 0;
        v_min_time_diff_number number;
        v_min_tx_value number;
        v_max_tx_value number;
begin

    SELECT unit_value into v_min_time_diff_number from FD_BUSINESS_RULES where unit = 'Minimum Time Frequency';
    SELECT unit_value into v_min_tx_value from FD_BUSINESS_RULES where unit = 'Approved Purchase';
    SELECT unit_value into v_max_tx_value from FD_BUSINESS_RULES where unit = 'Rejected Purchase';

    SELECT id
      INTO v_ccid 
      FROM cc_fd
     WHERE cc_no = :new.credit_card_no;   
    if inserting then
        if :new.total_pay < v_min_tx_value then
                :new.transaction_status := 'APPROVED';
                :new.comments := 'Lower than minimum amount of $ '||v_min_tx_value||'';
        elsif :new.total_pay >= v_min_tx_value AND :new.total_pay < v_max_tx_value then
                :new.transaction_status := 'OnHold';
                :new.trans_status := 'UNREAD';
        else 
                :new.transaction_status := 'REJECTED';
                :new.comments := 'Higher than allowed amount of $ '||v_max_tx_value||'';
        end if; 
        :new.cc_id := v_ccid;   
       --v_n := my_dashboard ('Hi');
    --DBMS_OUTPUT.PUT_LINE('Sales 2017: ' || l_sales_2017);
   end if;     
   
end;
/
ALTER TRIGGER "RETAIL_SHOPPING_FD_TRG" ENABLE;
*/