-- Table for holding credit card information -- please do not use real credit card numbers -- these are auto generated
  CREATE TABLE "CC_FD" 
   (	"ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"CUST_ID" NUMBER, 
	"CC_NO" NUMBER, 
	"STATUS" VARCHAR2(50), 
	"VALIDITY" DATE, 
	"FIRST_NAME" VARCHAR2(50), 
	"LAST_NAME" VARCHAR2(50), 
	"BANK_NAME" VARCHAR2(50), 
	"COMMENTS" VARCHAR2(100), 
	"CARD_TYPE" VARCHAR2(10), 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

-- Table for holding transaction information

  CREATE TABLE "RETAIL_SHOPPING_FD" 
   (	"ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"INV_NO" VARCHAR2(50), 
	"GENDER" VARCHAR2(50), 
	"AGE" NUMBER, 
	"CATEGORY" VARCHAR2(50), 
	"QTY" NUMBER, 
	"PRICE" NUMBER, 
	"TOTAL_PAY" NUMBER, 
	"METHOD" VARCHAR2(50), 
	"INV_DATE" TIMESTAMP (6), 
	"MALL" VARCHAR2(50), 
	"CUST_ID" NUMBER, 
	"CUST_FIRST_NAME" VARCHAR2(100), 
	"CUST_LAST_NAME" VARCHAR2(100), 
	"CREDIT_CARD_NO" NUMBER, 
	"TRANS_STATUS" VARCHAR2(20), 
	"CUST_CITY" VARCHAR2(100), 
	"CUST_STATE_PROVINCE" VARCHAR2(100), 
	"TRANSACTION_STATUS" VARCHAR2(50), 
	"COMMENTS" VARCHAR2(500), 
	"COUNTRY_ID" VARCHAR2(50), 
	"TX_TIMESTAMP" TIMESTAMP (6), 
	"MERCHANT_ID" NUMBER, 
	"MERCHANT_CITY" VARCHAR2(50), 
	"MERCHANT_REGION" VARCHAR2(255), 
	"MERCHANT_STATE" VARCHAR2(100), 
	"MERCHANT_PLACE" VARCHAR2(100), 
	"LONGITUDE" NUMBER, 
	"LATITUDE" NUMBER, 
	"MERCHANT_PLACE_ID" NUMBER, 
	"CUSTOMER_FULLNAME" VARCHAR2(50), 
	"MERCHANT_FULLNAME" VARCHAR2(50), 
	"INV_TIMESTAMP" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"CC_ID" NUMBER, 
	"TIME_DIFFERENCE_NUMBER" NUMBER, 
	"TX_TYPE" VARCHAR2(20), 
	"WORKFLOW_STATUS" VARCHAR2(100), 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "RETAIL_SHOPPING_FD_TRG" 
before 
insert on "RETAIL_SHOPPING_FD"  
for each row 
declare 
        v_ccid number; 
        v_n number := 0; 
        v_min_time_diff_number number; 
        v_min_tx_value number; 
        v_max_tx_value number; 
begin 
 
    SELECT unit_value into v_min_time_diff_number from FD_BUSINESS_RULES where unit = 'Minimum Time Frequency'; 
    SELECT unit_value into v_min_tx_value from FD_BUSINESS_RULES where unit = 'Approved Purchase'; 
    SELECT unit_value into v_max_tx_value from FD_BUSINESS_RULES where unit = 'Rejected Purchase'; 
 
    SELECT id 
      INTO v_ccid  
      FROM cc_fd 
     WHERE cc_no = :new.credit_card_no;    
    if inserting then 
        if :new.total_pay < v_min_tx_value then 
                :new.transaction_status := 'APPROVE'; 
                :new.comments := 'Lower than minimum amount of $ '||v_min_tx_value||''; 
        elsif :new.total_pay >= v_min_tx_value AND :new.total_pay < v_max_tx_value then 
                :new.transaction_status := 'OnHold'; 
                :new.trans_status := 'UNREAD'; 
        else  
                :new.transaction_status := 'REJECT'; 
                :new.comments := 'Higher than allowed amount of $ '||v_max_tx_value||''; 
        end if;  
        :new.cc_id := v_ccid;     
   end if;      
    
end;
/
ALTER TRIGGER "RETAIL_SHOPPING_FD_TRG" ENABLE;

-- FD Business Rules 
  CREATE TABLE "FD_BUSINESS_RULES" 
   (	"ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"UNIT" VARCHAR2(50), 
	"UNIT_VALUE" NUMBER, 
	"DESCRIPTION" VARCHAR2(32767), 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

