create table TEST_TBL1 (
    id             number generated by default on null as identity
                   constraint test_tbl1_id_pk primary key,
    update_date    date
);

create or replace procedure TEST_TBL1_PROC is
begin
  INSERT INTO TEST_TBL1 (update_date) values (sysdate);
  commit;
end;

begin
  dbms_scheduler.create_job (
     job_name           =>  'My_Test_Table_Job',
     job_type           =>  'STORED_PROCEDURE',
     job_action         =>  'TEST_TBL1_PROC',
     start_date         =>  systimestamp, 
     repeat_interval    =>  'freq=secondly; interval = 2;',
     enabled            =>  true,
     comments           => 'My new job'
  );
end;

 begin
  DBMS_SCHEDULER.RUN_JOB('My_Test_Table_Job');
 end;

select count(*) from TEST_TBL1;

Begin 
 dbms_scheduler.disable('My_Test_Table_Job',TRUE );  
End;

Begin 
 dbms_scheduler.drop_job(job_name => 'My_Test_Table_Job');
End;

drop table TEST_TBL1;